---
title: "test under contraints of intervals"
author: "SDMLAB"
date: \today
fontsize: 12pt
output:
   pdf_document:
     includes:
       in_header: Markdown.tex
     number_sections: yes
editor_options: 
  chunk_output_type: console
---

# data generations
```{r, echo=FALSE, results='hide', message=FALSE, warning=FALSE, fig.align='center', fig.width=5, fig.height=5}
rm(list = ls())
source("lib_SDLU.R")
source("csdlu-test.R")
set.seed(5)
n = 500
x = sort(runif(n, 0, 1))
f = 2.5 * x + 0.2 * sin((3 * x)^2)
y = f + rnorm(n) * 0.1
par(mfrow = c(1, 1))
plot(x, y, col = "grey")
lines(x, f, col = "black")
```


# interval $[1, 2]$
```{r, echo=FALSE, results='hide', message=FALSE, warning=FALSE, fig.align='center', fig.width=7, fig.height=4}
set.seed(3)
lambdas = 0
number_nodes = 8
range = max(x) - min(x)
width = c(1, 2)/ 4
widths = runif(number_nodes, width[1], width[2])
initial_values = initial_values_SDLU(x, number_nodes, widths)
beta = initial_values$beta
alpha1 = initial_values$alpha1
alpha0 = initial_values$alpha0
fit = sdlu(response = y, predictor = cbind(x), number_nodes = number_nodes, 
           lambdas = lambdas, initial_bias = 0, 
           initial_beta = beta, width = width,
           initial_alpha0 = alpha0, initial_alpha1 = alpha1, 
           verbose = T)
# save(file = "csdl_results/fit1", fit1)
```

## activated planes and fitted function
```{r, echo=FALSE, results='hide', message=FALSE, warning=FALSE, fig.align='center', fig.width=7, fig.height=3.5}
index = 1 #which.min(fit$aic_list)
par(mfrow = c(1, 2), pty = "s")
matplot(x, t(t(fit[[index]]$active_planes)*fit[[index]]$beta), type = "l", lty = 1,
        ylab = bquote(~sigma))
plot(x, y, col = "grey")
lines(x, fit[[index]]$fitted_values, col = "red", lwd = 2)
```

## check widths of fitted activation functions
```{r echo=FALSE}
abs(2 / fit[[1]]$alpha1)
```


# interval $[1, 2]$
```{r, echo=FALSE, results='hide', message=FALSE, warning=FALSE, fig.align='center', fig.width=7, fig.height=4}
set.seed(3)
lambdas = 0
number_nodes = 4
range = max(x) - min(x)
width = c(1, 2) / 2
widths = runif(number_nodes, width[1], width[2])
initial_values = initial_values_SDLU(x, number_nodes, widths)
beta = initial_values$beta
alpha1 = initial_values$alpha1
alpha0 = initial_values$alpha0

residual = y - fit[[1]]$fitted_values
fit_res = sdlu(response = residual, predictor = cbind(x), number_nodes = number_nodes, 
           lambdas = lambdas, initial_bias = 0, 
           initial_beta = beta, width = width,
           initial_alpha0 = alpha0, initial_alpha1 = alpha1, 
           verbose = T)
```

## activated planes and fitted function
```{r, echo=FALSE, results='hide', message=FALSE, warning=FALSE, fig.align='center', fig.width=7, fig.height=3.5}
index = 1 #which.min(fit$aic_list)
par(mfrow = c(1, 2), pty = "s")
plot(x, y, col = "grey")
lines(x, fit[[index]]$fitted_values, col = "red", lwd = 2)

plot(x, y, col = "grey")
lines(x, fit_res[[index]]$fitted_values + fit[[index]]$fitted_values, col = "blue", lwd = 2)
```


# for loop - global fitting
```{r, echo=FALSE, results='hide', message=FALSE, warning=FALSE, fig.align='center', fig.width=7, fig.height=3.5}
number_nodes_list = c(4, 8, 16, 32, 64, 128)

for (number_node in number_nodes_list)
{
  set.seed(3)
  lambdas = 0
  number_nodes = number_node
  range = max(x) - min(x)
  width = c(1, 2) 
  widths = runif(number_nodes, width[1], width[2])
  initial_values = initial_values_SDLU(x, number_nodes, widths)
  beta = initial_values$beta
  alpha1 = initial_values$alpha1
  alpha0 = initial_values$alpha0
  fit = sdlu(response = y, predictor = cbind(x), number_nodes = number_nodes, 
           lambdas = lambdas, initial_bias = 0, 
           initial_beta = beta, width = width,
           initial_alpha0 = alpha0, initial_alpha1 = alpha1, 
           verbose = T)
  
  index = 1 #which.min(fit$aic_list)
  par(mfrow = c(1, 2), pty = "s")
  matplot(x, t(t(fit[[index]]$active_planes)*fit[[index]]$beta), type = "l", lty = 1,
        ylab = bquote(~sigma), main = 'Activation function')
  plot(x, y, col = "grey", main = paste('The number of nodes: ', number_nodes))
  lines(x, fit[[index]]$fitted_values, col = "red", lwd = 2)
}
```

