---
title: "Bayes decision boundary"
author: "SDMLAB"
date: \today
fontsize: 11pt
output:
   pdf_document:
     includes:
       in_header: Markdown.tex
     number_sections: yes
editor_options: 
  chunk_output_type: console
---

# 1. Load ESL data
```{r, fig.width = 8, fig.height = 8, results = 'hide'}
load("ESL.mixture.rda")
set.seed(15)
x = ESL.mixture$x
y = ESL.mixture$y

means = ESL.mixture$means # 10 means from each class
```

# 2. ESL data plot
```{r}
par(mfrow = c(1, 1), pty = 's')
plot(x, type = 'n', xlab = 'x1', ylab = 'x2', main = "ESL mixture data")
points(x[1:100,], col = "blue", cex = 1.2)
points(x[101:200,], col = "orange", cex = 1.2)
```


# 3. Bayes decision boundary
```{r}
prob = ESL.mixture$prob # true probability at 1
px1 = ESL.mixture$px1
px2 = ESL.mixture$px2
xgrid=expand.grid(x1 = px1, x2 = px2)

par(pty="s")
plot(xgrid, type = 'n', main = 'Bayes decision boundary',xlab = expression(x[1]), ylab = expression(x[2]))
points(xgrid[(sign(prob-0.5) == -1), ], col = "blue", cex = 0.1)
points(xgrid[(sign(prob-0.5) == 1), ], col = "orange", cex = 0.1)
points(x[1:100,], col = "blue", cex = 1.2)
points(x[101:200,], col = "orange", cex = 1.2)
contour(px1,px2,matrix(prob,69,99), level = 0.5, add=TRUE, col="black", lwd = 1, drawlabels = F) #optimal boundary
```


# 4. Bayes error rate: the lowest possible error rate for any classifier of a random outcome
```{r}
bayes_error = sum(ESL.mixture$marginal * (prob * I(prob < 0.5) + (1 - prob) * I(prob >= .5)))
```

